### ISSUE TITLE
Organize column makes column disappear

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/Web-Karma#225]
In the following example, I use organize columns to hide all but the first two columns:
![2016-03-21_09-56-11](https://cloud.githubusercontent.com/assets/1074599/13926856/6a88d420-ef4b-11e5-9c32-72c463d161c4.png)

The result is missing one column
![2016-03-21_09-56-31](https://cloud.githubusercontent.com/assets/1074599/13926866/731dc0dc-ef4b-11e5-89d6-60c2622d7697.png)

and the exception is
```
ERROR [2016-03-21 09:56:14,786] (VWorksheet->generateOrganizedColumns->278): Error organizing column:{"visible":false,"hideable":true,"name":20130965,"id":"HN13"}
org.json.JSONException: JSONObject["name"] not a string.
	at org.json.JSONObject.getString(JSONObject.java:658)
	at edu.isi.karma.view.VWorksheet.generateOrganizedColumns(VWorksheet.java:268)
	at edu.isi.karma.view.VWorksheet.organizeColumns(VWorksheet.java:287)
	at edu.isi.karma.controller.command.worksheet.OrganizeColumnsCommand.orderColumns(OrganizeColumnsCommand.java:82)
	at edu.isi.karma.controller.command.worksheet.OrganizeColumnsCommand.doIt(OrganizeColumnsCommand.java:56)
	at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:162)
```

The input file is `https://github.com/usc-isi-i2/uk-hack/blob/master/data/profiles/www.1919a4.com/extractions/www.1919a4.com_extractions_test_filtered.jl`

**Comment by dkapoor** [comment]
Issue was with it not being able to handle columns with numeric column names. Have fixed the issue.
