### ISSUE TITLE
Set Semantic Type dies in mixed number/string column

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/Web-Karma#226]
Input file:
`https://github.com/usc-isi-i2/uk-hack/blob/master/data/profiles/www.1919a4.com/extractions/www.1919a4.com_extractions_test_filtered.jl`

I do set semantic type on the `19621180` column and get the following exception:
```
WARN [2016-03-21 10:03:35,639] (HybridSTModelHandler->predictType->286): KS test called
java.lang.NumberFormatException: For input string: "1,414"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at edu.isi.karma.semantictypes.typinghandler.HybridSTModelHandler.predictType(HybridSTModelHandler.java:300)
	at edu.isi.karma.modeling.semantictypes.SemanticTypeUtil.predictColumnSemanticType(SemanticTypeUtil.java:226)
	at edu.isi.karma.controller.command.alignment.GetSemanticSuggestionsCommand$1.generateJson(GetSemanticSuggestionsCommand.java:80)

```

**Comment by szeke** [comment]
It is ok to patch this up so it doesn't die as we will soon replace the semantic typer with the new service

**Comment by dkapoor** [comment]
Have fixed this issue. The regex for detecting number allows a comma in data. However the code for collecting examples was reading it using Double.parseDouble that does not allow commas. So have fixed this and am using NumberFormat to parse values now.
