### ISSUE TITLE
Getting errors when trying to publish R2RML model

### ISSUE THREAD

**Issue by chen-regen** [usc-isi-i2/Web-Karma#255]
I am getting following exceptions when trying to publish R2RML model.

```
ERROR [2016-04-25 09:07:14,775] (KR2RMLMappingGenerator->addWorksheetHistory->136): Worksheet history file not found! Can't write worksheet history into R2RML model. Path:C:\development\karma_home\models-autosave/WSP1WS8-RI-demo-data_Sheet1-auto-model.ttl
INFO [2016-04-25 09:07:14,783] (R2RMLAlignmentFileSaver->saveAlignment->103): Time to generate mappings:19msec
ERROR [2016-04-25 09:07:14,824] (GenerateR2RMLModelCommand->doIt->337): Error occured while generating R2RML Model!
java.lang.NullPointerException
        at edu.isi.karma.kr2rml.KR2RMLMappingWriter.addCompleteWorksheetHistory(KR2RMLMappingWriter.java:435)
        at edu.isi.karma.kr2rml.KR2RMLMappingWriter.addKR2RMLMappingResource(KR2RMLMappingWriter.java:115)
        at edu.isi.karma.kr2rml.KR2RMLMappingWriter.addR2RMLMapping(KR2RMLMappingWriter.java:141)
        at edu.isi.karma.controller.command.alignment.R2RMLAlignmentFileSaver.writeModel(R2RMLAlignmentFileSaver.java:127)
        at edu.isi.karma.controller.command.alignment.R2RMLAlignmentFileSaver.saveAlignment(R2RMLAlignmentFileSaver.java:107)
        at edu.isi.karma.controller.command.alignment.R2RMLAlignmentFileSaver.saveAlignment(R2RMLAlignmentFileSaver.java:79)
        at edu.isi.karma.controller.command.alignment.GenerateR2RMLModelCommand.doIt(GenerateR2RMLModelCommand.java:284)
        at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:162)
        at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:130)
        at edu.isi.karma.webserver.ExecutionController.invokeCommand(ExecutionController.java:129)
        at edu.isi.karma.webserver.RequestController.doPost(RequestController.java:99)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:201)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:445)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)
```

I also noticed that the "models-autosave" folder is empty. I don't see any ttl files created. Other folders have files saved like "user-uploaded-files", "models-json", etc. Is this a permission issue (I am on Windows 7 Enterprise)?

**Comment by dkapoor** [comment]
Yes, it does look like a permission issue. It is not able to write to your karma home folder. Can you give write access to the karma home folder and try again. Thanks.

**Comment by chen-regen** [comment]
Hi,
Thank you for your response!
I checked my folder permissions and they are all the same as "rwxr-xr-x". "modules-autosave" folder has the same permission as other folders like "user-uploaded-files", "models-json", etc. And Karma has no problems to save files in those folders. Can you tell what difference would make saving into "modules-autosave" fail?

```
drwxr-xr-x    1 cwen         4096 Apr 22 11:44 karma_home/
```

```
drwxr-xr-x    1 cwen            0 Apr 22 11:44 models-autosave/
drwxr-xr-x    3 cwen            0 Apr 22 11:46 models-json/
drwxr-xr-x    1 cwen            0 Apr 22 11:45 user-uploaded-files/
```

**Comment by dkapoor** [comment]
Can you try doing what is mentioned in Step 4 of the Troubleshooting page in the wiki: https://github.com/usc-isi-i2/Web-Karma/wiki/Troubleshooting
It could be because of some file locking issue in Windows.

**Comment by chen-regen** [comment]
I suppose you mean to say step 5. I actually did that when I installed Karma. I recompiled everything and started up karma again just now. It worked. Thank you for your help.
