### ISSUE TITLE
Error while publishing updated model

### ISSUE THREAD

**Issue by nikunjgala** [usc-isi-i2/Web-Karma#257]
Karma Version - v2.045
Scenario : I had a model already saved and wanted to make some changes and save updated model. I imported data again and applied saved model. After doing updates, I got error while publishing model again.
Error message in UI : Error occured while generating R2RML model!
Error Log on console:
`INFO [2016-05-05 12:08:56,287] (R2RMLAlignmentFileSaver->saveAlignment->108): Alignment for WSP2:WS5 saved to file: C:\Users\Nikunj\karma\models-autosave/WSP1WS5-target.csv-auto-model.ttl`
`INFO [2016-05-05 12:08:56,297] (R2RMLAlignmentFileSaver->saveAlignment->110): Time to write to file:482msec
storeOldHistory: false`
`ERROR [2016-05-05 12:09:04,747] (CommandHistoryUtil->replayHistory->157): Fail to replay history`
`java.io.IOException: Stream Closed
        at java.io.FileInputStream.read0(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:207)
        at org.apache.commons.io.input.BOMInputStream.getBOM(BOMInputStream.java:218)
        at org.apache.commons.io.input.BOMInputStream.readFirstBytes(BOMInputStream.java:262)
        at org.apache.commons.io.input.BOMInputStream.read(BOMInputStream.java:335)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at edu.isi.karma.imp.csv.CSVImport.generateWorksheet(CSVImport.java:85)
        at edu.isi.karma.controller.history.CommandHistoryUtil.replayHistory(CommandHistoryUtil.java:126)
        at edu.isi.karma.controller.history.CommandHistoryUtil.replayHistory(CommandHistoryUtil.java:118)
        at edu.isi.karma.controller.command.alignment.GenerateR2RMLModelCommand.doIt(GenerateR2RMLModelCommand.java:149)
        at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:162)
        at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:130)
        at edu.isi.karma.webserver.ExecutionController.invokeCommand(ExecutionController.java:129)
        at edu.isi.karma.webserver.RequestController.doPost(RequestController.java:99)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:201)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:445)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)`
`INFO [2016-05-05 12:09:04,912] (GraphUtil->exportJson->489): exporting the graph to json ...`
`INFO [2016-05-05 12:09:04,928] (GraphUtil->exportJson->507): export is done.`
`INFO [2016-05-05 12:09:04,932] (GraphVizUtil->exportJGraphToGraphviz->277): exporting the graph to graphviz ...`
`INFO [2016-05-05 12:09:04,946] (GraphVizUtil->exportJGraphToGraphviz->288): export is done.`
`INFO [2016-05-05 12:09:04,950] (R2RMLAlignmentFileSaver->saveAlignment->95): Time to get alignment info for saving: 0msec`
`INFO [2016-05-05 12:09:04,970] (R2RMLAlignmentFileSaver->saveAlignment->103): Time to generate mappings:20msec`
`ERROR [2016-05-05 12:09:04,975] (GenerateR2RMLModelCommand->doIt->337): Error occured while generating R2RML Model!`
`java.io.FileNotFoundException: C:\Web-Karma\karma-web\src\main\webapp\publish\R2RML\target.csv-model.ttl (The requested operation cannot be performed on a file with a user-mapped section open)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at java.io.PrintWriter.<init>(PrintWriter.java:192)
        at java.io.PrintWriter.<init>(PrintWriter.java:303)
        at edu.isi.karma.controller.command.alignment.R2RMLAlignmentFileSaver.writeModel(R2RMLAlignmentFileSaver.java:124)
        at edu.isi.karma.controller.command.alignment.R2RMLAlignmentFileSaver.saveAlignment(R2RMLAlignmentFileSaver.java:107)
        at edu.isi.karma.controller.command.alignment.R2RMLAlignmentFileSaver.saveAlignment(R2RMLAlignmentFileSaver.java:79)
        at edu.isi.karma.controller.command.alignment.GenerateR2RMLModelCommand.doIt(GenerateR2RMLModelCommand.java:284)
        at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:162)
        at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:130)
        at edu.isi.karma.webserver.ExecutionController.invokeCommand(ExecutionController.java:129)
        at edu.isi.karma.webserver.RequestController.doPost(RequestController.java:99)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:201)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:445)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)`

However, I could save a copy from autosaved models folder which had all updates worked perfectly fine upon retrying to apply it.

**Comment by dkapoor** [comment]
Nikunj, Can you try Step 5 mentioned in the troubleshooting section: https://github.com/usc-isi-i2/Web-Karma/wiki/Troubleshooting.
