### ISSUE TITLE
running karma-offline as jar

### ISSUE THREAD

**Issue by kojinanjo** [usc-isi-i2/Web-Karma#258]
Hi

I'm trying to run karma-offline as jar. 
First I had made the package with "mvn package" in the Web-Karma directory, then in the karma-offline folder I found a karma-oofline-0.0.1-SNAPSHOT.jar but I can't run it.

"java -cp karma-offline-0.0.1-SNAPSHOT.jar edu.isi.karma.rdf.OfflineRdfGenerator --sourcetype CSV --filepath "datos.csv" --modelfilepath "modelo.ttl" --sourcename datos --outputfile exportado.ttl" 

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: edu/isi/karma/metadata/KarmaMetadata
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: edu.isi.karma.metadata.KarmaMetadata
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more"

Can you give me a hand please?

Thanks

**Comment by dkapoor** [comment]
You run it as a jar, please do the following
```
cd Web-Karma
mvn clean install
cd karma-offline
mvn install -P shaded
```
This will create `karma-offline-0.0.1-SNAPSHOT-shaded.jar` in the `target` subfolder of `karma-offline`. You can use that to run Karma as a jar in offline mode.

`java -cp karma-offline-0.0.1-SNAPSHOT-shaded.jar edu.isi.karma.rdf.OfflineRdfGenerator --sourcetype CSV --filepath "datos.csv" --modelfilepath "modelo.ttl" --sourcename datos --outputfile exportado.ttl`

**Comment by kojinanjo** [comment]
thank you! you saved me life :)
