### ISSUE TITLE
UnrecognizedOptionException

### ISSUE THREAD

**Issue by gigialmo88** [usc-isi-i2/Web-Karma#266]
**I am at the step to generate a RDF of a database table. First I cd karma-offline. Then I put in my arguments into the terminal:**

mvn exec:java -Dexec.mainClass="edu.isi.karma.rdf.OfflineRdfGenerator" -Dexec.args=" --source
type DB --dbtype MySQL --hostname <hostname> --username <username> --password <password> --portnumber <portnumber> --dbname <dbname> --tablename <tablename> --outputfile db-rdf.n3 -Dexec.classpathScope=compile

**For the arguments in <> I have those filled out, but for security purposes left them out in this message.** 

**Once I execute I receive this error message:**

ERROR [2016-06-22 11:22:42,237] (CommandLineArgumentParser->parse->34): Error oc
cured while parsing arguments!
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -Dexec.
classpathScope=compile
        at org.apache.commons.cli.Parser.processOption(Parser.java:363)
        at org.apache.commons.cli.Parser.parse(Parser.java:199)
        at org.apache.commons.cli.Parser.parse(Parser.java:85)
        at edu.isi.karma.rdf.CommandLineArgumentParser.parse(CommandLineArgument
Parser.java:26)
        at edu.isi.karma.rdf.OfflineRdfGenerator.main(OfflineRdfGenerator.java:1
40)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:290)
        at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.493 s
[INFO] Finished at: 2016-06-22T11:22:42-06:00
[INFO] Final Memory: 15M/223M
[INFO] ------------------------------------------------------------------------

Am I missing some arguments that are required? My intention is just to view the rdf output of a table from the MySQL DB. 

Thanks!

**Comment by dkapoor** [comment]
Apologies for the late reply. There is a quote missing in your statement after db-rdf.n3

mvn exec:java -Dexec.mainClass="edu.isi.karma.rdf.OfflineRdfGenerator" -Dexec.args=" --source
type DB --dbtype MySQL --hostname --username --password --portnumber --dbname --tablename --outputfile db-rdf.n3" -Dexec.classpathScope=compile
