### ISSUE TITLE
Error when import xml file

### ISSUE THREAD

**Issue by binh-vu** [usc-isi-i2/Web-Karma#275]
Karma version 2.047 throws these error when I try to import this xml file (attached):

[test.xml.zip](https://github.com/usc-isi-i2/Web-Karma/files/461085/test.xml.zip)

ERROR [2016-09-08 00:50:24,923] (WorksheetCleaningUpdate->generateJson->172): Error while invoking cleaning service
org.apache.http.NoHttpResponseException: The target server failed to respond
       	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
       	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:62)
       	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:254)
       	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:289)
       	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:252)
       	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:191)
       	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:300)
       	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:127)
       	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:716)
       	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:521)
       	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
       	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
       	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
       	at edu.isi.karma.util.HTTPUtil.invokeHTTPRequest(HTTPUtil.java:102)
       	at edu.isi.karma.util.HTTPUtil.executeHTTPPostRequest(HTTPUtil.java:64)
       	at edu.isi.karma.util.HTTPUtil.executeHTTPPostRequest(HTTPUtil.java:77)
       	at edu.isi.karma.controller.update.WorksheetCleaningUpdate.generateJson(WorksheetCleaningUpdate.java:134)
       	at edu.isi.karma.controller.update.UpdateContainer.generateJson(UpdateContainer.java:87)
       	at edu.isi.karma.controller.update.UpdateContainer.generateJson(UpdateContainer.java:120)
       	at edu.isi.karma.webserver.RequestController.doPost(RequestController.java:79)
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
       	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
       	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505)
       	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
       	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564)
       	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
       	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
       	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
       	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
       	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030)
       	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
       	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:201)
       	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
       	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
       	at org.eclipse.jetty.server.Server.handle(Server.java:445)
       	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268)
       	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
       	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
       	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
       	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
       	at java.lang.Thread.run(Thread.java:745)
ERROR [2016-09-08 00:50:24,934] (WorksheetCleaningUpdate->generateJson->172): Error while invoking cleaning service
org.apache.http.NoHttpResponseException: The target server failed to respond
       	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
       	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:62)
       	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:254)
       	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:289)
       	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:252)
       	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:191)
       	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:300)
       	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:127)
       	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:716)
       	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:521)
       	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
       	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
       	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
       	at edu.isi.karma.util.HTTPUtil.invokeHTTPRequest(HTTPUtil.java:102)
       	at edu.isi.karma.util.HTTPUtil.executeHTTPPostRequest(HTTPUtil.java:64)
       	at edu.isi.karma.util.HTTPUtil.executeHTTPPostRequest(HTTPUtil.java:77)
       	at edu.isi.karma.controller.update.WorksheetCleaningUpdate.generateJson(WorksheetCleaningUpdate.java:134)
       	at edu.isi.karma.controller.update.UpdateContainer.generateJson(UpdateContainer.java:87)
       	at edu.isi.karma.controller.update.UpdateContainer.generateJson(UpdateContainer.java:120)
       	at edu.isi.karma.webserver.RequestController.doPost(RequestController.java:79)
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
       	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
       	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505)
       	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
       	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564)
       	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
       	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
       	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
       	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
       	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030)
       	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
       	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:201)
       	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
       	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
       	at org.eclipse.jetty.server.Server.handle(Server.java:445)
       	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268)
       	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
       	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
       	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
       	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
       	at java.lang.Thread.run(Thread.java:745)
ERROR [2016-09-08 00:50:24,939] (WorksheetCleaningUpdate->generateJson->172): Error while invoking cleaning service
org.apache.http.NoHttpResponseException: The target server failed to respond
       	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
       	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:62)
       	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:254)
       	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:289)
       	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:252)
       	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:191)
       	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:300)
       	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:127)
       	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:716)
       	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:521)
       	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
       	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
       	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
       	at edu.isi.karma.util.HTTPUtil.invokeHTTPRequest(HTTPUtil.java:102)
       	at edu.isi.karma.util.HTTPUtil.executeHTTPPostRequest(HTTPUtil.java:64)
       	at edu.isi.karma.util.HTTPUtil.executeHTTPPostRequest(HTTPUtil.java:77)
       	at edu.isi.karma.controller.update.WorksheetCleaningUpdate.generateJson(WorksheetCleaningUpdate.java:134)
       	at edu.isi.karma.controller.update.UpdateContainer.generateJson(UpdateContainer.java:87)
       	at edu.isi.karma.controller.update.UpdateContainer.generateJson(UpdateContainer.java:120)
       	at edu.isi.karma.webserver.RequestController.doPost(RequestController.java:79)
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
       	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
       	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505)
       	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
       	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564)
       	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
       	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
       	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
       	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
       	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030)
       	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
       	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:201)
       	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
       	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
       	at org.eclipse.jetty.server.Server.handle(Server.java:445)
       	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268)
       	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
       	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
       	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
       	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
       	at java.lang.Thread.run(Thread.java:745)
ERROR [2016-09-08 00:50:24,944] (WorksheetCleaningUpdate->generateJson->172): Error while invoking cleaning service
org.apache.http.NoHttpResponseException: The target server failed to respond
       	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
       	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:62)
       	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:254)
       	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:289)
       	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:252)
       	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:191)
       	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:300)
       	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:127)
       	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:716)
       	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:521)
       	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
       	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
       	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
       	at edu.isi.karma.util.HTTPUtil.invokeHTTPRequest(HTTPUtil.java:102)
       	at edu.isi.karma.util.HTTPUtil.executeHTTPPostRequest(HTTPUtil.java:64)
       	at edu.isi.karma.util.HTTPUtil.executeHTTPPostRequest(HTTPUtil.java:77)
       	at edu.isi.karma.controller.update.WorksheetCleaningUpdate.generateJson(WorksheetCleaningUpdate.java:134)
       	at edu.isi.karma.controller.update.UpdateContainer.generateJson(UpdateContainer.java:87)
       	at edu.isi.karma.controller.update.UpdateContainer.generateJson(UpdateContainer.java:120)
       	at edu.isi.karma.webserver.RequestController.doPost(RequestController.java:79)
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
       	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
       	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505)
       	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
       	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564)
       	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
       	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
       	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
       	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
       	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030)
       	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
       	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:201)
       	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
       	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
       	at org.eclipse.jetty.server.Server.handle(Server.java:445)
       	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268)
       	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
       	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
       	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
       	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
       	at java.lang.Thread.run(Thread.java:745)
...

**Comment by dkapoor** [comment]
I tried importing the file and it loads up fine.
How are u running Karma? Are you using `mvn jetty:run`? When Karma starts, it also bring up apps in the karma-web/external_webapps folder. It seems those are not running for you.

**Comment by binh-vu** [comment]
Hello,

I have try the same file on my friend machine and it works fine. I try to re-installed it (completely swept Karma and Karma HOME) but the error still there. I guess may be it's a problem with my local environment so I install it on docker and it works fine.

Thank you for your help.
