### ISSUE TITLE
Error when trying to delete Operate Selection:Union

### ISSUE THREAD

**Issue by mayaram00** [usc-isi-i2/Web-Karma#276]
Created a selection to add rows
Tried to delete it using the command history

ERROR [2016-09-09 15:44:03,678](CommandHistoryUtil->replayHistory->163): Fail to replay history
java.io.IOException: Stream Closed
    at java.io.FileInputStream.read0(Native Method)
    at java.io.FileInputStream.read(FileInputStream.java:207)
    at org.apache.commons.io.input.BOMInputStream.getBOM(BOMInputStream.java:218)
    at org.apache.commons.io.input.BOMInputStream.readFirstBytes(BOMInputStream.java:262)
    at org.apache.commons.io.input.BOMInputStream.read(BOMInputStream.java:335)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.BufferedReader.fill(BufferedReader.java:161)
    at java.io.BufferedReader.readLine(BufferedReader.java:324)
    at java.io.BufferedReader.readLine(BufferedReader.java:389)
    at edu.isi.karma.imp.csv.CSVImport.generateWorksheet(CSVImport.java:85)
    at edu.isi.karma.controller.history.CommandHistoryUtil.replayHistory(CommandHistoryUtil.java:133)
    at edu.isi.karma.controller.history.CommandHistoryUtil.replayHistory(CommandHistoryUtil.java:125)
    at edu.isi.karma.controller.command.alignment.ExportOrDeleteHistoryCommand.doIt(ExportOrDeleteHistoryCommand.java:81)
    at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:167)
    at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:130)
    at edu.isi.karma.webserver.ExecutionController.invokeCommand(ExecutionController.java:129)
    at edu.isi.karma.webserver.RequestController.doPost(RequestController.java:99)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:201)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:445)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
    at java.lang.Thread.run(Thread.java:745)
ERROR [2016-09-09 15:44:14,909](CommandHistoryUtil->replayHistory->163): Fail to replay history
java.io.IOException: Stream Closed
    at java.io.FileInputStream.read0(Native Method)
    at java.io.FileInputStream.read(FileInputStream.java:207)
    at org.apache.commons.io.input.BOMInputStream.getBOM(BOMInputStream.java:218)
    at org.apache.commons.io.input.BOMInputStream.readFirstBytes(BOMInputStream.java:262)
    at org.apache.commons.io.input.BOMInputStream.read(BOMInputStream.java:335)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.BufferedReader.fill(BufferedReader.java:161)
    at java.io.BufferedReader.readLine(BufferedReader.java:324)
    at java.io.BufferedReader.readLine(BufferedReader.java:389)
    at edu.isi.karma.imp.csv.CSVImport.generateWorksheet(CSVImport.java:85)
    at edu.isi.karma.controller.history.CommandHistoryUtil.replayHistory(CommandHistoryUtil.java:133)
    at edu.isi.karma.controller.history.CommandHistoryUtil.replayHistory(CommandHistoryUtil.java:125)
    at edu.isi.karma.controller.command.alignment.ExportOrDeleteHistoryCommand.doIt(ExportOrDeleteHistoryCommand.java:81)
    at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:167)
    at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:130)
    at edu.isi.karma.webserver.ExecutionController.invokeCommand(ExecutionController.java:129)
    at edu.isi.karma.webserver.RequestController.doPost(RequestController.java:99)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:201)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:445)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
    at java.lang.Thread.run(Thread.java:745)

**Comment by dkapoor** [comment]
Maya, I am not able to reproduce this. Can you send me your karma home folder, your input dataset and also the model up to the point before you try to delete the selection. I can try to delete it and see if I can reproduce it. Thanks.
Also, what OS are u running Karma on?

**Comment by dkapoor** [comment]
There was an issue re-reading CSV files. The Reader got closed after importing Worksheet and subsequently anything that needed to re-generate the worksheet (Which this command does need) would not work. This has been fixed and I tried it on a CSV file and it works.
