### ISSUE TITLE
Unable to publish model to github using latest karma development branch in Windows

### ISSUE THREAD

**Issue by raviraju** [usc-isi-i2/Web-Karma#304]
INFO [2016-12-13 14:42:51,280] (WorksheetR2RMLJenaModelParser->loadSourceModelIntoJenaModel->219): Load model:http://localhost:8080/R2RMLMapping/local/WAM_XMLExport_AAC_Objects.xml-model.ttl

INFO [2016-12-13 14:42:54,448] (SaveR2RMLModelCommand->doIt->138): Saved model to triple store
INFO [2016-12-13 14:42:54,449] (GenerateR2RMLModelCommand->doIt->314): Saved model to triple store
ERROR [2016-12-13 14:42:54,762] (ExecutionController->getCommand->120): Command PublishGithubCommand not found!
java.lang.NullPointerException
        at edu.isi.karma.controller.history.WorksheetCommandHistory.getWorksheetId(WorksheetCommandHistory.java:163)
        at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:138)
        at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:130)
        at edu.isi.karma.webserver.ExecutionController.invokeCommand(ExecutionController.java:129)
        at edu.isi.karma.webserver.RequestController.doPost(RequestController.java:99)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:201)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:445)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)

**Comment by dkapoor** [comment]
I know you switched from using the App to the source code version.
Can you make sure you are in development branch. It looks to me that you are on master.
`git branch` will show you the branch you are in. Switch to development and do the following: 
```
> git checkout development
> git pull
> mvn clean install -Dmaven.test.skip=true
> cd karma-web
> mvn jetty:run
```
When you start your browser, empty your cache and then open karma page.

**Comment by raviraju** [comment]
Working fine
