### ISSUE TITLE
Error with PublishReportCommandparseerror

### ISSUE THREAD

**Issue by sjayakum** [usc-isi-i2/Web-Karma#323]
PFA the screenshot and logs

<img width="1680" alt="screen shot 2017-03-28 at 3 36 52 pm" src="https://cloud.githubusercontent.com/assets/12380569/24431464/d7e97178-13d0-11e7-997d-d520dbc20f50.png">

```
ERROR [2017-03-28 15:41:18,114] (PublishReportCommand$1->generateJson->140): Error generating report
java.lang.NullPointerException
	at edu.isi.karma.controller.command.publish.PublishReportCommand.getClassName(PublishReportCommand.java:453)
	at edu.isi.karma.controller.command.publish.PublishReportCommand.access$900(PublishReportCommand.java:43)
	at edu.isi.karma.controller.command.publish.PublishReportCommand$2.compare(PublishReportCommand.java:392)
	at edu.isi.karma.controller.command.publish.PublishReportCommand$2.compare(PublishReportCommand.java:389)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:239)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at edu.isi.karma.controller.command.publish.PublishReportCommand.writeSemanticTypes(PublishReportCommand.java:389)
	at edu.isi.karma.controller.command.publish.PublishReportCommand.access$500(PublishReportCommand.java:43)
	at edu.isi.karma.controller.command.publish.PublishReportCommand$1.generateJson(PublishReportCommand.java:123)
	at edu.isi.karma.controller.update.UpdateContainer.generateJson(UpdateContainer.java:87)
	at edu.isi.karma.controller.update.UpdateContainer.generateJson(UpdateContainer.java:120)
	at edu.isi.karma.webserver.RequestController.doPost(RequestController.java:104)

```

**Comment by kaushalv274** [comment]
Hi Suraj,

Please share model, data, ontology files.

Thanks
Kaushal

**Comment by dkapoor** [comment]
Kaushal has resolved this issue and the changes are merged into development. You can pull in the changes and rebuild karma to get the fix. Thanks.
