### ISSUE TITLE
PROBLEM LAUNCHING KARMA

### ISSUE THREAD

**Issue by PedroMoreo** [usc-isi-i2/Web-Karma#350]
hello, 

I install one click install, 2.053 under windows, https://github.com/usc-isi-i2/Web-Karma/wiki/Installation%3A-One-Click-Install first day it works , but no more again. 
I can't launch it.

"

ago 31, 2017 9:47:15 AM org.apache.catalina.startup.ContextConfig beforeStart
GRAVE: Excepción arreglando docBase: 
java.io.IOException: Invalid argument
	at java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:428)
	at java.io.File.getCanonicalPath(File.java:618)
	at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:117)
	at org.apache.catalina.startup.ContextConfig.fixDocBase(ContextConfig.java:737)
	at org.apache.catalina.startup.ContextConfig.beforeStart(ContextConfig.java:862)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:390)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:388)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:144)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

ago 31, 2017 9:47:16 AM org.apache.catalina.loader.WebappClassLoaderBase validateJarFile
INFORMACIÓN: validateJarFile(C:\Karma-Windows\resources\app\tomcat\work\Catalina\localhost\_\WEB-INF\lib\javax.servlet-3.0.0.v201112011016.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
ago 31, 2017 9:47:39 AM org.apache.catalina.startup.TaglibUriRule body
INFORMACIÓN: TLD skipped. URI: urn:com:sun:jersey:api:view is already defined
ago 31, 2017 9:47:40 AM org.apache.catalina.startup.TldConfig execute
INFORMACIÓN: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
ago 31, 2017 9:47:40 AM org.apache.catalina.startup.HostConfig deployWAR
INFORMACIÓN: Deployment of web application archive C:\Karma-Windows\resources\app\tomcat\webapps\ROOT.war has finished in 25.394 ms
ago 31, 2017 9:47:40 AM org.apache.coyote.AbstractProtocol start
INFORMACIÓN: Starting ProtocolHandler ["http-bio-8080"]

"

Can somebody help me?

**Comment by kaushalv274** [comment]
Hi Pedro,

Can you try following steps and let us know whether it works or not. 

(1) Try Rebooting your PC and start Karma again.
(2) Uninstall Karma and Install again from the web.
     Try running Karma. (Check your JRE_HOME is set properly.)

Did you end Karma abruptly before it stopped working ?

Thanks
Kaushal

**Comment by PedroMoreo** [comment]
Hello Kaushal, for your early reply

I tried 1) , and I think, I did well 2) , but there is not much to do in the install.. just .. unzip.
Karma did no end abruptly, just 2ºnd time I start it, it did not work.

C:\Users\pjmo>echo %Java_HOME%
C:\software\Java\jdk1.8.0_141

C:\Users\pjmo>echo %JRE_HOME%
 c:\software\Java\jre1.8.0_141

I think variables are fine. so I don't know what else, can I do.

**Comment by PedroMoreo** [comment]
Finally reinstall jdk and reset the JAVA_HOME WORKED .
