### ISSUE TITLE
Error: Failed to Store Data to TripleStore

### ISSUE THREAD

**Issue by kateblanch** [usc-isi-i2/Web-Karma#381]
Hello, can you help me understand what is causing this error? Attached is my data and my model. When I attempt to Publish > To RDF I get this error "Failed to Store Data to TripleStore". 
Any help would be appreciated!

--Change the extension of this file to "ttl" to get the model = DigInObjects_v7_2-18-2018-model.txt
[DigInObjects_v7_2-18-2018-model.txt](https://github.com/usc-isi-i2/Web-Karma/files/1872535/DigInObjects_v7_2-18-2018-model.txt)

--
[DigInObject_4-3-2018.txt](https://github.com/usc-isi-i2/Web-Karma/files/1872537/DigInObject_4-3-2018.txt)

**Comment by kateblanch** [comment]
Here are the logs from the Tomcat service...
 INFO [http-nio-8080-exec-1] (Alignment.java:938) - Time to compute the Alignment: 0.125sec
 INFO [http-nio-8080-exec-1] (ApplyHistoryFromR2RMLModelCommand.java:213) - Time taken to Apply R2RML Model: 7sec
 INFO [http-nio-8080-exec-3] (GetClassesCommand.java:162) - Got 188 classes from OntologyManager
 INFO [http-nio-8080-exec-2] (FetchGraphsFromTripleStoreCommand.java:86) - Graphs fetched : 1
 INFO [http-nio-8080-exec-13] (TripleStoreUtil.java:188) - http://localhost:8080/openrdf-sesame/repositories/karma_data/size
data.okeeffemuseum.org/
s
ERROR [http-nio-8080-exec-9] (KR2RMLMappingGenerator.java:95) - Unable to create mapping identifier
java.net.MalformedURLException: no protocol: data.okeeffemuseum.org/s3cbec7c4-5081-4a9a-8d69-e3af5a77eeaf
        at java.base/java.net.URL.<init>(URL.java:627)
        at java.base/java.net.URL.<init>(URL.java:523)
        at java.base/java.net.URL.<init>(URL.java:470)
        at edu.isi.karma.kr2rml.mapping.KR2RMLMappingGenerator.<init>(KR2RMLMappingGenerator.java:93)
        at edu.isi.karma.kr2rml.mapping.KR2RMLMappingGenerator.<init>(KR2RMLMappingGenerator.java:77)
        at edu.isi.karma.controller.command.publish.PublishRDFCommand.doIt(PublishRDFCommand.java:188)
        at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:232)
        at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:142)
        at edu.isi.karma.webserver.ExecutionController.invokeCommand(ExecutionController.java:129)
        at edu.isi.karma.webserver.RequestController.doPost(RequestController.java:99)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:844)
 INFO [http-nio-8080-exec-9] (PublishRDFCommand.java:238) - RDF written to file: C:\Users\Kate\Desktop\Karma-Windows\Karma-Windows\resources\app\tomcat\webapps\ROOT\/publish/RDF/WSP1WS5.ttl
 INFO [http-nio-8080-exec-9] (PublishRDFCommand.java:277) - tripleStoreURl : http://localhost:8080/openrdf-sesame/repositories/karma_data
 INFO [http-nio-8080-exec-9] (TripleStoreUtil.java:836) - Repository URL : http://localhost:8080/openrdf-sesame/repositories/karma_data
 INFO [http-nio-8080-exec-9] (TripleStoreUtil.java:188) - http://localhost:8080/openrdf-sesame/repositories/karma_data/size
 INFO [http-nio-8080-exec-9] (TripleStoreUtil.java:820) - Connection Test passed
 INFO [http-nio-8080-exec-9] (TripleStoreUtil.java:1038) - Using PUT to save rdf to triple store
 INFO [http-nio-8080-exec-9] (DefaultRequestDirector.java:697) - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:8080: Connection reset by peer: socket write error
 INFO [http-nio-8080-exec-9] (DefaultRequestDirector.java:707) - Retrying request to {}->http://localhost:8080
 INFO [http-nio-8080-exec-9] (DefaultRequestDirector.java:697) - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:8080: Connection reset by peer: socket write error
 INFO [http-nio-8080-exec-9] (DefaultRequestDirector.java:707) - Retrying request to {}->http://localhost:8080
 INFO [http-nio-8080-exec-9] (DefaultRequestDirector.java:697) - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:8080: Connection reset by peer: socket write error
 INFO [http-nio-8080-exec-9] (DefaultRequestDirector.java:707) - Retrying request to {}->http://localhost:8080
java.net.SocketException: Connection reset by peer: socket write error
        at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at org.apache.http.impl.io.AbstractSessionOutputBuffer.write(AbstractSessionOutputBuffer.java:179)
        at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:113)
        at org.apache.http.entity.FileEntity.writeTo(FileEntity.java:99)
        at org.apache.http.entity.HttpEntityWrapper.writeTo(HttpEntityWrapper.java:94)
        at org.apache.http.impl.client.EntityEnclosingRequestWrapper$EntityWrapper.writeTo(EntityEnclosingRequestWrapper.java:112)
        at org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:118)
        at org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:263)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.sendRequestEntity(ManagedClientConnectionImpl.java:216)
        at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:686)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:488)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at edu.isi.karma.er.helper.TripleStoreUtil.saveToStore(TripleStoreUtil.java:1043)
        at edu.isi.karma.er.helper.TripleStoreUtil.saveToStoreFromFile(TripleStoreUtil.java:1081)
        at edu.isi.karma.controller.command.publish.PublishRDFCommand.doIt(PublishRDFCommand.java:280)
        at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:232)
        at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:142)
        at edu.isi.karma.webserver.ExecutionController.invokeCommand(ExecutionController.java:129)
        at edu.isi.karma.webserver.RequestController.doPost(RequestController.java:99)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:844)
ERROR [http-nio-8080-exec-9] (TripleStoreUtil.java:1056) - java.net.SocketException : Connection reset by peer: socket write error
ERROR [http-nio-8080-exec-9] (PublishRDFCommand.java:302) - Falied to store rdf to karma_data store

**Comment by rutujarane** [comment]
Please reopen this issue if you are still facing this problem.
Closing.

**Comment by p-tulgaa** [comment]
I face same issue when i was about to publish RDF, in my case used just play json file as worksheet then applied Generated suggestion model.

if someone do know solution please let me know.

`
ERROR [2020-12-03 11:16:23,987] (TripleStoreUtil->saveToStore->1062): java.net.SocketException : Broken pipe
ERROR [2020-12-03 11:16:23,988] (PublishRDFCommand->doIt->302): Falied to store rdf to karma_data store`


also there is prequel messages states
`
ERROR [2020-12-03 11:16:15,716] (KR2RMLMappingGenerator->addWorksheetHistory->140): Worksheet history file not found! Can't write worksheet history into R2RML model. Path:/Users/tulgaa/karma/models-autosave/WSP1WS7-course-2020-autumn.json-auto-model.ttl
`

**Comment by p-tulgaa** [comment]
> Please reopen this issue if you are still facing this problem.
> Closing.

Could you please reopen this issue, for me its not possible since i'm not the author
