### ISSUE TITLE
offline mode randomly times out

### ISSUE THREAD

**Issue by GreatYYX** [usc-isi-i2/Web-Karma#388]
1. model works well for data in gui.
2. in offline mode, it randomly fails while applying the model.
3. tried to split file into small pieces, same as 2, randomly failed on different pieces.
4. tried to use default memory size, 8gb 10gb and 20 gb heap, same as 2.
5. set memory size to 4gb (magic number?), it worked. (for some other datasets, 4gb doesn't work)

*. server has enough idle cpu and memory resources.

don't know if there's a dead lock in multithreading implementation. I can help to reproduce.

error message:
```
ERROR [2018-05-29 17:28:22,797] (TriplesMapPlanExecutor->execute->88): Unable to finish executing plan
java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at edu.isi.karma.kr2rml.planning.TriplesMapPlanExecutor.execute(TriplesMapPlanExecutor.java:84)
        at edu.isi.karma.kr2rml.KR2RMLWorksheetRDFGenerator.generateRDF(KR2RMLWorksheetRDFGenerator.java:234)
        at edu.isi.karma.rdf.GenericRDFGenerator.generateRDF(GenericRDFGenerator.java:187)
        at edu.isi.karma.rdf.GenericRDFGenerator.generateRDF(GenericRDFGenerator.java:143)
        at edu.isi.karma.rdf.GenericRDFGenerator.generateRDF(GenericRDFGenerator.java:220)
        at edu.isi.karma.rdf.OfflineRdfGenerator.generateRdfFromFile(OfflineRdfGenerator.java:613)
        at edu.isi.karma.rdf.OfflineRdfGenerator.generateRDF(OfflineRdfGenerator.java:181)
        at edu.isi.karma.rdf.OfflineRdfGenerator.generate(OfflineRdfGenerator.java:164)
        at edu.isi.karma.rdf.OfflineRdfGenerator.main(OfflineRdfGenerator.java:150)
ERROR [2018-05-29 17:28:22,798] (TriplesMapWorker->call->84): Error while waiting for dependent triple maps to process
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at edu.isi.karma.kr2rml.planning.TriplesMapWorker.call(TriplesMapWorker.java:80)
        at edu.isi.karma.kr2rml.planning.TriplesMapPlanExecutor$1.call(TriplesMapPlanExecutor.java:78)
        at edu.isi.karma.kr2rml.planning.TriplesMapPlanExecutor$1.call(TriplesMapPlanExecutor.java:72)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at edu.isi.karma.kr2rml.planning.TriplesMapPlanExecutor.execute(TriplesMapPlanExecutor.java:84)
        at edu.isi.karma.kr2rml.KR2RMLWorksheetRDFGenerator.generateRDF(KR2RMLWorksheetRDFGenerator.java:234)
        at edu.isi.karma.rdf.GenericRDFGenerator.generateRDF(GenericRDFGenerator.java:187)
        at edu.isi.karma.rdf.GenericRDFGenerator.generateRDF(GenericRDFGenerator.java:143)
        at edu.isi.karma.rdf.GenericRDFGenerator.generateRDF(GenericRDFGenerator.java:220)
        at edu.isi.karma.rdf.OfflineRdfGenerator.generateRdfFromFile(OfflineRdfGenerator.java:613)
        at edu.isi.karma.rdf.OfflineRdfGenerator.generateRDF(OfflineRdfGenerator.java:181)
        at edu.isi.karma.rdf.OfflineRdfGenerator.generate(OfflineRdfGenerator.java:164)
        at edu.isi.karma.rdf.OfflineRdfGenerator.main(OfflineRdfGenerator.java:150)
```

line in code: https://github.com/usc-isi-i2/Web-Karma/blob/e4aac8008894245b9efa7fcb67bf459caea45842/karma-common/src/main/java/edu/isi/karma/kr2rml/planning/TriplesMapWorker.java#L84

**Comment by GreatYYX** [comment]
the above fix doesn't work. switching to use thread pool can temporarily solve this issue  -> https://github.com/usc-isi-i2/Web-Karma/blob/e4aac8008894245b9efa7fcb67bf459caea45842/karma-common/src/main/java/edu/isi/karma/kr2rml/KR2RMLWorksheetRDFGenerator.java#L216  replace `false` to `true`

**Comment by GreatYYX** [comment]
Closing, fixed in https://github.com/usc-isi-i2/Web-Karma/commit/9788ccc401722380d66418046745111aa4f6e3ec .
Previous fix (https://github.com/usc-isi-i2/Web-Karma/commit/c1a718ee44f0754aba45a9413cd6e44393cf7aa8) is not correct and it's on master, needs to be reverted.
