### ISSUE TITLE
Apply R2RML Model: "Error occured while applying history!"

### ISSUE THREAD

**Issue by VincentDucatteeuw** [usc-isi-i2/Web-Karma#493]
**Description of the bug**
I am mapping a CSV to CIDOC CRM in Karma-web. I have saved my mapping model and would like to proceed my work that I have done by doing an "Apply R2RML Model" on the original CSV. 

**To Reproduce**
1. Upload original and unedited CSV
2. Click on "Apply R2RML Model"
3. See error

**Expected behavior**
After applying the R2RML Model to the original CSV, I would expect all previously done commands to be done on the CSV.

**Screenshots**
![image](https://user-images.githubusercontent.com/81633268/123073899-22e98e00-d417-11eb-9ec1-f6eb532eab6e.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome

**Additional context from Tomcat**
```
 INFO [http-nio-8080-exec-6] (TripleStoreUtil.java:836) - Repository URL : http://localhost:8080/openrdf-sesame/repositories/karma_models
 INFO [http-nio-8080-exec-6] (TripleStoreUtil.java:188) - http://localhost:8080/openrdf-sesame/repositories/karma_models/size
 INFO [http-nio-8080-exec-6] (TripleStoreUtil.java:820) - Connection Test passed
 INFO [http-nio-8080-exec-9] (WorksheetR2RMLJenaModelParser.java:219) - Load model:file:/C:/Users/vducatte/Downloads/Karma-Windows/Karma-Windows/resources/app/tomcat/bin/tmp.ttl
ERROR [http-nio-8080-exec-9] (ApplyHistoryFromR2RMLModelCommand.java:178) - Error occured while applying history!
edu.isi.karma.webserver.KarmaException: Resource not found in model for the source: karma_mapping_straten_gent_1855.csv
        at edu.isi.karma.kr2rml.mapping.WorksheetR2RMLJenaModelParser.parse(WorksheetR2RMLJenaModelParser.java:130)
        at edu.isi.karma.controller.command.worksheet.ApplyHistoryFromR2RMLModelCommand.extractHistoryFromModel(ApplyHistoryFromR2RMLModelCommand.java:223)
        at edu.isi.karma.controller.command.worksheet.ApplyHistoryFromR2RMLModelCommand.doIt(ApplyHistoryFromR2RMLModelCommand.java:139)
        at edu.isi.karma.controller.command.worksheet.ApplyModelFromURLCommand.doIt(ApplyModelFromURLCommand.java:67)
        at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:232)
        at edu.isi.karma.controller.history.CommandHistory.doCommand(CommandHistory.java:142)
        at edu.isi.karma.webserver.ExecutionController.invokeCommand(ExecutionController.java:129)
        at edu.isi.karma.webserver.RequestController.doPost(RequestController.java:99)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1627)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by Bidisha010496** [comment]
Hi we have made a new release for the Karma-App. Could you please check and confirm if you are still facing the same issue ?
