### ISSUE TITLE
getFileMagic() only operates on streams which support mark(int)

### ISSUE THREAD

**Issue by EmidioStani** [usc-isi-i2/Web-Karma#519]
**Describe the bug**
Error when importing an Excel file

**To Reproduce**
Import -> from File -> select Excel spreadsheet

**Expected behavior**
Being able to open the file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 97
 - Version: 2.5.2
 - 
**Additional context**
I tried to import different Excel files and I have an error:

INFO [http-nio-8080-exec-2] (ImportPropertiesUpdate.java:38) - Got encoding: UTF-8
 INFO [http-nio-8080-exec-3] (ToCSV.java:443) - Opening workbook [test.xlsx]
ERROR [http-nio-8080-exec-3] (ImportExcelFileCommand.java:82) - Error occured while converting the Excel file to CSV file.
java.io.IOException: getFileMagic() only operates on streams which support mark(int)
        at org.apache.poi.poifs.filesystem.FileMagic.valueOf(FileMagic.java:131)
        at org.apache.poi.poifs.filesystem.NPOIFSFileSystem.hasPOIFSHeader(NPOIFSFileSystem.java:370)

See attachment
[test.xlsx](https://github.com/usc-isi-i2/Web-Karma/files/8016701/test.xlsx)

**Comment by Bidisha010496** [comment]
This is fixed now. Kindly reopen if the issue isn't resolved in your system.
